---
# VolumeSnapshotClass for RDS CSI Driver
# Requires VolumeSnapshot CRDs to be installed cluster-wide:
#   kubectl kustomize https://github.com/kubernetes-csi/external-snapshotter/client/config/crd | kubectl create -f -
# And snapshot-controller to be deployed:
#   kubectl kustomize https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller | kubectl create -f -
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: rds-csi-snapclass
  labels:
    app: rds-csi
driver: rds.csi.srvlab.io
deletionPolicy: Delete
# parameters: {}
# No special parameters needed for Btrfs snapshots.
# Optional parameters that can be added:
#   btrfsFSLabel: "storage-pool"  # Override Btrfs filesystem label (default: storage-pool)
